### PR TITLE
Improve error reporting

### PR DESCRIPTION
**Pull request by vesln**
Thoughts?

screen shot 2014-01-11 at 8 09 43 pm

@logicalparadox @RStankov @jkroso

### CODE REVIEW

**Comment by logicalparadox** [comment]
Is the "no stack" because Chai had showStack as false or because hydro had it as false?

**Comment by vesln** [comment]
There is no stack because I set ``err.stack = null`.

Point taken though, it should be its responsibility, not chai's.

**Comment by logicalparadox** [comment]
chai can pass along the 'showStack' property with each error, then hydro will know not to include it for a given error. Alternatively it could be a hydro all-or-nothing option. I just want display to not be chai's responsibility, which it currently is.

**Comment by logicalparadox** [comment]
Mainly because the way Chai currently handles it is by not capturing the stack at all, which was a design mistake (that I made) imho.

**Comment by vesln** [comment]
Agreed with hydro handling this. Both `error.showStack` and `hydro.set('showStack', true)` could be respected. I love it.

**Comment by jkroso** [comment]
LGTM. though i'd prefer to switch `Failures/Error: {msg}` for just `{msg}`. Either that or provide an error type. Like `Equality Error: {msg}`, `Type Error`, etc.. but that would be tricky. Having all error messages prefixed with the same thing would annoy me I think.

Likewise with noisy stack traces. Do you think we should hide the node.js module loading parts of the stack trace by default?

**Comment by vesln** [comment]
Fair point about `Failures/Error`, I will change it.

I also want to make Chai.js telling us which type of assertion was performed (`deep.equal`, `include` etc..), this would make the error reporting even more useful imho.

Cleaner error stacks is something I'm REALLY passionate about. I think we could test ideas on [hydro-clean-stacks](http://github.com/hydrojs/hydro-clean-stacks) and at some point merge it into hydro.

**Comment by logicalparadox** [comment]
For `Failures/Error: {msg}` I think that as long as the error has that type of `AssertionError` then you can omit the type (as that is what is expected for test failures. However, if it is any other kind of error (plain `Error`, `ReferenceError`, etc...) then I think the type should be displayed.

**Comment by vesln** [comment]
Great idea!

**Comment by jkroso** [comment]
Just made the changes we discussed +1 more. This is the end result

untitled copy

**Comment by jkroso** [comment]
I'll merge and release for now but we can continue the discussion here

**Comment by vesln** [comment]
Looks good to me

**Pull request merged**
